import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient({
  datasources: {
    db: {
      url: process.env.DATABASE_URL,
    },
  },
});

async function main() {
  console.log("Seed iniciado");

await prisma.game.deleteMany();

await prisma.game.createMany({
  data: [
    {
      titulo: "Cyberpunk 2077",
      genero: "RPG",
      precio: 59.99,
      imagen: "https://cdn.akamai.steamstatic.com/steam/apps/1091500/capsule_616x353.jpg",
      rating: 4.2,
      isFavorite: false,
      anio: 2020,
      plataformas: "PC, PS5, Xbox Series X/S",
      descripcion: "Juego de rol de mundo abierto ambientado en Night City.",
      developer: "CD Projekt Red",
    },
    {
      titulo: "The Witcher 3: Wild Hunt",
      genero: "RPG",
      precio: 39.99,
      imagen: "https://cdn.akamai.steamstatic.com/steam/apps/292030/capsule_616x353.jpg",
      rating: 4.9,
      isFavorite: false,
      anio: 2015,
      plataformas: "PC, PS5, Xbox Series X/S, Switch",
      descripcion: "Aventura épica protagonizada por Geralt de Rivia.",
      developer: "CD Projekt Red",
    },
    {
      titulo: "Elden Ring",
      genero: "Action RPG",
      precio: 59.99,
      imagen: "https://cdn.akamai.steamstatic.com/steam/apps/1245620/capsule_616x353.jpg",
      rating: 4.8,
      isFavorite: false,
      anio: 2022,
      plataformas: "PC, PS5, Xbox Series X/S",
      descripcion: "Mundo abierto de fantasía creado por FromSoftware.",
      developer: "FromSoftware",
    },
    {
      titulo: "Red Dead Redemption 2",
      genero: "Action Adventure",
      precio: 49.99,
      imagen: "https://cdn.akamai.steamstatic.com/steam/apps/1174180/capsule_616x353.jpg",
      rating: 4.9,
      isFavorite: false,
      anio: 2019,
      plataformas: "PC, PS4, Xbox One",
      descripcion: "Aventura en el viejo oeste estadounidense.",
      developer: "Rockstar Games",
    },
    {
      titulo: "Grand Theft Auto V",
      genero: "Action",
      precio: 29.99,
      imagen: "https://cdn.akamai.steamstatic.com/steam/apps/271590/capsule_616x353.jpg",
      rating: 4.7,
      isFavorite: false,
      anio: 2015,
      plataformas: "PC, PS5, Xbox Series X/S",
      descripcion: "Sandbox criminal en Los Santos.",
      developer: "Rockstar Games",
    },
    {
      titulo: "Hades",
      genero: "Roguelike",
      precio: 24.99,
      imagen: "https://cdn.akamai.steamstatic.com/steam/apps/1145360/capsule_616x353.jpg",
      rating: 4.7,
      isFavorite: false,
      anio: 2020,
      plataformas: "PC, PS5, Xbox, Switch",
      descripcion: "Roguelike basado en la mitología griega.",
      developer: "Supergiant Games",
    },
    {
      titulo: "Hollow Knight",
      genero: "Metroidvania",
      precio: 14.99,
      imagen: "https://cdn.akamai.steamstatic.com/steam/apps/367520/capsule_616x353.jpg",
      rating: 4.9,
      isFavorite: false,
      anio: 2017,
      plataformas: "PC, PS4, Xbox One, Switch",
      descripcion: "Exploración y combate en Hallownest.",
      developer: "Team Cherry",
    },
    {
      titulo: "Stardew Valley",
      genero: "Simulation",
      precio: 14.99,
      imagen: "https://cdn.akamai.steamstatic.com/steam/apps/413150/capsule_616x353.jpg",
      rating: 4.8,
      isFavorite: false,
      anio: 2016,
      plataformas: "PC, PS4, Xbox One, Switch",
      descripcion: "Simulador de granja y vida rural.",
      developer: "ConcernedApe",
    },
    {
      titulo: "Terraria",
      genero: "Sandbox",
      precio: 9.99,
      imagen: "https://cdn.akamai.steamstatic.com/steam/apps/105600/capsule_616x353.jpg",
      rating: 4.8,
      isFavorite: false,
      anio: 2011,
      plataformas: "PC, PS4, Xbox One, Switch",
      descripcion: "Aventura sandbox en 2D.",
      developer: "Re-Logic",
    },
    {
      titulo: "Baldur's Gate 3",
      genero: "RPG",
      precio: 59.99,
      imagen: "https://cdn.akamai.steamstatic.com/steam/apps/1086940/capsule_616x353.jpg",
      rating: 4.9,
      isFavorite: false,
      anio: 2023,
      plataformas: "PC, PS5",
      descripcion: "RPG basado en Dungeons & Dragons.",
      developer: "Larian Studios",
    },
    {
      titulo: "God of War",
      genero: "Action Adventure",
      precio: 49.99,
      imagen: "https://cdn.akamai.steamstatic.com/steam/apps/1593500/capsule_616x353.jpg",
      rating: 4.8,
      isFavorite: false,
      anio: 2022,
      plataformas: "PC, PS5",
      descripcion: "La aventura de Kratos y Atreus.",
      developer: "Santa Monica Studio",
    },
    {
      titulo: "Marvel's Spider-Man Remastered",
      genero: "Action Adventure",
      precio: 59.99,
      imagen: "https://cdn.akamai.steamstatic.com/steam/apps/1817070/capsule_616x353.jpg",
      rating: 4.7,
      isFavorite: false,
      anio: 2022,
      plataformas: "PC, PS5",
      descripcion: "El héroe arácnido en Nueva York.",
      developer: "Insomniac Games",
    },
    {
      titulo: "Sekiro: Shadows Die Twice",
      genero: "Action",
      precio: 59.99,
      imagen: "https://cdn.akamai.steamstatic.com/steam/apps/814380/capsule_616x353.jpg",
      rating: 4.8,
      isFavorite: false,
      anio: 2019,
      plataformas: "PC, PS4, Xbox One",
      descripcion: "Acción desafiante en Japón feudal.",
      developer: "FromSoftware",
    },
    {
      titulo: "Dark Souls III",
      genero: "Action RPG",
      precio: 39.99,
      imagen: "https://cdn.akamai.steamstatic.com/steam/apps/374320/capsule_616x353.jpg",
      rating: 4.8,
      isFavorite: false,
      anio: 2016,
      plataformas: "PC, PS4, Xbox One",
      descripcion: "La conclusión de la saga Dark Souls.",
      developer: "FromSoftware",
    },
    {
      titulo: "Resident Evil 4",
      genero: "Survival Horror",
      precio: 59.99,
      imagen: "https://cdn.akamai.steamstatic.com/steam/apps/2050650/capsule_616x353.jpg",
      rating: 4.8,
      isFavorite: false,
      anio: 2023,
      plataformas: "PC, PS5, Xbox Series X/S",
      descripcion: "Remake del clásico de terror.",
      developer: "Capcom",
    },
    {
      titulo: "Monster Hunter: World",
      genero: "Action RPG",
      precio: 29.99,
      imagen: "https://cdn.akamai.steamstatic.com/steam/apps/582010/capsule_616x353.jpg",
      rating: 4.6,
      isFavorite: false,
      anio: 2018,
      plataformas: "PC, PS4, Xbox One",
      descripcion: "Caza monstruos gigantes en ecosistemas vivos.",
      developer: "Capcom",
    },
    {
      titulo: "Valheim",
      genero: "Survival",
      precio: 19.99,
      imagen: "https://cdn.akamai.steamstatic.com/steam/apps/892970/capsule_616x353.jpg",
      rating: 4.6,
      isFavorite: false,
      anio: 2021,
      plataformas: "PC, Xbox Series X/S",
      descripcion: "Supervivencia cooperativa inspirada en la mitología nórdica.",
      developer: "Iron Gate Studio",
    },
    {
      titulo: "Factorio",
      genero: "Strategy",
      precio: 35.00,
      imagen: "https://cdn.akamai.steamstatic.com/steam/apps/427520/capsule_616x353.jpg",
      rating: 4.9,
      isFavorite: false,
      anio: 2020,
      plataformas: "PC",
      descripcion: "Automatización y construcción de fábricas.",
      developer: "Wube Software",
    },
    {
      titulo: "No Man's Sky",
      genero: "Exploration",
      precio: 59.99,
      imagen: "https://cdn.akamai.steamstatic.com/steam/apps/275850/capsule_616x353.jpg",
      rating: 4.4,
      isFavorite: false,
      anio: 2016,
      plataformas: "PC, PS5, Xbox Series X/S",
      descripcion: "Exploración espacial procedural.",
      developer: "Hello Games",
    },
    {
      titulo: "Cities: Skylines",
      genero: "Simulation",
      precio: 29.99,
      imagen: "https://cdn.akamai.steamstatic.com/steam/apps/255710/capsule_616x353.jpg",
      rating: 4.7,
      isFavorite: false,
      anio: 2015,
      plataformas: "PC, PS4, Xbox One",
      descripcion: "Simulador de construcción de ciudades.",
      developer: "Colossal Order",
    },
  ],
});



  console.log("Seed OK");
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());